//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzly.Store.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string itemName { get; set; }
        public Nullable<int> itemPrice { get; set; }
        public Nullable<int> itemsCount { get; set; }
        public Nullable<int> storeId { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
